routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('main.index');
Route::resource('first', 'FirstController');
Route::resource('second', 'SecondController');
Route::resource('third', 'ThirdController');
Route::resource('fourth', 'FourthController');

app/Models/Bid.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bid extends Model
{
    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    public $fillable = [
        'event_id',
        'name',
        'email',
        'price',
    ];
}

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    public $fillable = ['caption'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use App\Traits\MagnificentBag;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests, MagnificentBag;
}

app/Http/Controllers/FirstController.php
<?php

namespace App\Http\Controllers;

use App\Services\QueryServiceInterface;

class FirstController extends Controller
{

    /**
     * @var \App\Services\QueryServiceInterface
     */
    protected $queryService;

    /**
     * FirstController constructor.
     *
     * @param  \App\Services\QueryServiceInterface  $queryService
     */
    public function __construct(QueryServiceInterface $queryService)
    {
        $this->queryService = $queryService;
    }

    public function index()
    {
        $dumps1 = $this->queryService->getUserWithHighPriceBids();
        $dumps2 = $this->queryService->getEventsWithoutBids();
        $dumps3 = $this->queryService->getEventsWithBidsMoreThanThree();
        $dumps4 = $this->queryService->getEventsWithBidsMoreAmount();

        return view('task1', compact('dumps1', 'dumps2', 'dumps3', 'dumps4'));
    }

}

app/Http/Controllers/FourthController.php
<?php

namespace App\Http\Controllers;

class FourthController extends Controller
{

    public function index()
    {
        list($a, $b) = $this->changeVariables();
        return view('task4', compact('a', 'b'));
    }

}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainController extends Controller
{

    public function index()
    {
        return view('home');
    }

}

app/Http/Controllers/SecondController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GeneralRequest;

class SecondController extends Controller
{

    /**
     * @param  \App\Http\Requests\GeneralRequest  $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(GeneralRequest $request)
    {
        if ($request->validated()) {
            list($amountPupils, $sportPupils, $percent) = $this->getAmountSportPupils($request->amount, $request->percent);
        } else {
            list($amountPupils, $sportPupils, $percent) = $this->getAmountSportPupils();
        }

        return view('task2', compact('amountPupils', 'sportPupils', 'percent'));
    }
}

app/Http/Controllers/ThirdController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GeneralRequest;

class ThirdController extends Controller
{

    public function index(GeneralRequest $request)
    {
        if ($request->validated()) {
            list($digits, $str) = $this->getDigitsFromString($request->string);
        } else {
            list($digits, $str) = $this->getDigitsFromString();
        }

        return view('task3', compact('digits', 'str'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Task 1')

@section('content')
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <a class="btn btn-primary btn-lg" href="{{ route('first.index') }}">Нажми и начнем!</a>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Semalt: @yield('title')</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Google fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('css/prettify.css') }}">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
</head>
<body>
<div class="site-wrap">
    @include('layouts.header')
    @yield('content')
</div>
<!-- Styles -->
<script type="text/javascript"
        src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="{{ asset('js/prettify.js') }}"></script>
<script type="text/javascript">
    !function ($) {
        $(function(){
            window.prettyPrint && prettyPrint()
        })
    }(window.jQuery)
</script>
</body>
</html>

resources/views/layouts/header.blade.php
<div class="bg-light pt-3 pb-3 mb-5">
    <div class="container">
        <div>
            <div class="d-flex justify-content-between align-items-center">
                <div class="logo">
                    <a href="/" class="navbar-brand">Semalt</a>
                </div>
                <div class="d-flex justify-content-end align-items-center">
                    <span class="navbar-text">Тестовое задание для компании "Semalt" (ver 1.0)</span>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/input-error.blade.php
@error($field)
<div class="invalid-feedback d-block">{{ $message }}</div>
@enderror

resources/views/layouts/tabs.blade.php
<div class="row mb-4">
    <div class="col-md-12 mb-5 mb-md-0">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link @menuactive('first') active @endmenuactive" href="{{ route('first.index') }}">Task 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link @menuactive('second') active @endmenuactive" href="{{ route('second.index') }}">Task 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link @menuactive('third') active @endmenuactive" href="{{ route('third.index') }}">Task 3</a>
            </li>
            <li class="nav-item">
                <a class="nav-link @menuactive('fourth') active @endmenuactive" href="{{ route('fourth.index') }}">Task 4</a>
            </li>
        </ul>
    </div>
</div>

resources/views/task1.blade.php
@extends('layouts.app')

@section('title', 'Task 1')

@section('content')
    <div class="site-section">
        <div class="container">
            @include('layouts.tabs')
            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                1. Сделать миграции
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
# Таблица Events
Schema::create('events', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('caption');
    $table->timestamps();
});

# Таблица Bids
Schema::create('bids', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->integer('event_id');
    $table->string('name');
    $table->string('email');
    $table->float('price');
    $table->timestamps();
});</pre>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo"
                                    aria-expanded="false" aria-controls="collapseTwo">
                                2. Запрос, который выберет имя пользователя (bids.name) с самой высокой ценой заявки
                                (bids.price)
                            </button>
                        </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
# Первый вариант
select name, price from bids order by price desc limit 1;

# Второй вариант
select name, price from bids where price in (select max(price) from bids);</pre>
                                <h6 class="mb-3">Результат выполнения</h6>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">User name</th>
                                        <th scope="col">Price</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($dumps1 as $dump1)
                                        @if($dump1)
                                            <tr>
                                                <td>{{ $dump1->name }}</td>
                                                <td>{{ number_format($dump1->price, 0, '.', ' ') }}</td>
                                            </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree"
                                    aria-expanded="false" aria-controls="collapseThree">
                                3. Запрос, который выберет название мероприятия (events.caption), по которому нет заявок
                            </button>
                        </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
# Первый вариант
select b.event_id as id, e.caption from events e
left join bids b on e.id = b.event_id
where b.event_id is null;

# Второй вариант
select e.caption from events e
join bids b on e.id not in (select event_id from bids)
group by e.caption;
</pre>
                                <h6 class="mb-3">Результат выполнения</h6>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Event caption</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($dumps2 as $dump2)
                                        @if($dump2)
                                            <tr>
                                                <td>{{ $dump2->caption }}</td>
                                            </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header" id="headingFour">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour"
                                    aria-expanded="false" aria-controls="collapseFour">
                                4. Запрос, который выберет название мероприятия (events.caption), по которому больше
                                трех заявок
                            </button>
                        </h5>
                    </div>
                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
select e.caption, count(b.event_id) as count from events e
join bids b on e.id = b.event_id
group by b.event_id
having count > 3
order by count desc;
</pre>
                                <h6 class="mb-3">Результат выполнения</h6>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Event caption</th>
                                        <th scope="col">Bids count</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($dumps3 as $dump3)
                                        @if($dump3)
                                            <tr>
                                                <td>{{ $dump3->caption }}</td>
                                                <td>{{ $dump3->count }}</td>
                                            </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header" id="headingFive">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFive"
                                    aria-expanded="false" aria-controls="collapseFive">
                                5. Запрос, который выберет название мероприятия (events.caption), по которому больше
                                всего заявок
                            </button>
                        </h5>
                    </div>
                    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
select e.caption, count(b.event_id) as count from events e
join bids b on e.id = b.event_id
group by b.event_id
having count > 3
limit 1;
</pre>
                                <h6 class="mb-3">Результат выполнения</h6>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Event caption</th>
                                        <th scope="col">Bids count</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($dumps4 as $dump4)
                                        @if($dump4)
                                            <tr>
                                                <td>{{ $dump4->caption }}</td>
                                                <td>{{ $dump4->count }}</td>
                                            </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/task2.blade.php
@extends('layouts.app')

@section('title', 'Task 2')

@section('content')
    <div class="site-section">
        <div class="container">
            @include('layouts.tabs')

            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                1. Написать алгоритм решения задачи
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Исходные данные</h6>
                                <pre class="prettyprint linenums">
В классе 28 учеников. 75% из них занимаются спортом. Сколько учеников в классе занимаются спортом?</pre>
                                <h6 class="mb-3">Свое значение (необязательно)</h6>
                                <form action="{{ route('second.index') }}" method="get">
                                    @csrf
                                    <div class="form-row align-items-center mb-4">
                                        <div class="col-auto">
                                            <label class="sr-only" for="amount">Amount</label>
                                            <input type="number" class="form-control" name="amount" id="amount" placeholder="Свое значение">
                                            @include('layouts.input-error', ['field' => 'amount'])
                                        </div>
                                        <div class="col-auto my-1">
                                            <label class="sr-only" for="percent">Percent</label>
                                            <select class="custom-select mr-sm-2" name="percent" id="percent">
                                                <option value="25">25%</option>
                                                <option value="50">50%</option>
                                                <option value="75">75%</option>
                                            </select>
                                            @include('layouts.input-error', ['field' => 'percent'])
                                        </div>
                                        <div class="col-auto">
                                            <button type="submit" class="btn btn-primary">Применить</button>
                                        </div>
                                    </div>
                                </form>
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
/**
  * @param  int  $amountPupils
  * @param  int  $percent
  * @return array
*/
public function getAmountSportPupils(int $amountPupils = 28, int $percent = 75): array
{
    $sportPupils = $amountPupils * $percent / 100;
    return [$amountPupils, (int)$sportPupils, $percent];
}</pre>
                            </div>
                            <h6 class="mb-3">Результат выполнения</h6>
                            <p>Всего учеников: <span class="badge badge-secondary">{{ $amountPupils }}</span></p>
                            <p>Ученики, которые занимаются спортом: <span class="badge badge-secondary">{{ $sportPupils }}</span></p>
                            <p>Выбранный процент: <span class="badge badge-secondary">{{ $percent }}</span></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/task3.blade.php
@extends('layouts.app')

@section('title', 'Task 3')

@section('content')
    <div class="site-section">
        <div class="container">
            @include('layouts.tabs')

            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                1. Реализовать алгоритм извлечения числовых значений со строки
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Исходные данные</h6>
                                <pre class="prettyprint linenums">
Default string: This server has 386 GB RAM and 500GB storage</pre>
                                <h6 class="mb-3">Свое значение (необязательно)</h6>
                                <form action="{{ route('third.index') }}" method="get">
                                    @csrf
                                    <div class="form-row align-items-center mb-4">
                                        <div class="col-auto">
                                            <label class="sr-only" for="string">String</label>
                                            <input type="text" class="form-control" name="string" id="string"
                                                   placeholder="Свое значение">
                                            @include('layouts.input-error', ['field' => 'string'])
                                        </div>
                                        <div class="col-auto">
                                            <button type="submit" class="btn btn-primary">Применить</button>
                                        </div>
                                    </div>
                                </form>
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
/**
  * @param  string  $str
  *
  * @return mixed
*/
public function getDigitsFromString($str = 'This server has 386 GB RAM and 500GB storage')
{
    preg_match_all("/\d+/", $str, $matches);
    return [$matches[0], $str];
}</pre>
                            </div>
                            <h6 class="mb-3">Результат выполнения</h6>
                            <p>Переданная строка: <span class="badge badge-secondary">{{ $str }}</span></p>
                            <p>Значения:
                                @foreach($digits as $digit)
                                    <span class="badge badge-secondary mr-1">{{ $digit }}</span>
                                @endforeach
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/task4.blade.php
@extends('layouts.app')

@section('title', 'Task 4')

@section('content')
    <div class="site-section">
        <div class="container">
            @include('layouts.tabs')

            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                1. Поменять 2 переменные местами без использования третьей
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            <div class="col-md-12">
                                <h6 class="mb-3">Исходные данные</h6>
                                <pre class="prettyprint linenums">
$а = [1,2,3,4,5];
$b = ‘Hello world’;</pre>
                                <p class="card-text"></p>
                                <p class="card-text"></p>
                                <h6 class="mb-3">Пример кода</h6>
                                <pre class="prettyprint linenums">
# Перывй вариант
/**
  * @return array
*/
public function changeVariables(): array
{
    $a = [1, 2, 3, 4, 5];
    $b = 'Hello world';

    array_push($a, $b);
    $b = $a;
    $a = array_pop($b);

    return [$a, $b];
}

# Второй вариант
/**
  * @return array
*/
public function changeVariables(): array
{
    $a = [1, 2, 3, 4, 5];
    $b = 'Hello world';

    list($b, $a) = [$a, $b];

    return [$a, $b];
}</pre>
                            </div>
                            <h6 class="mb-3">Результат выполнения</h6>
                            <p>Результат $a: <span class="badge badge-secondary mr-1">{{ $a }}</span></p>
                            <p>Результат $b:
                                @foreach($b as $digit)
                                    <span class="badge badge-secondary mr-1">{{ $digit }}</span>
                                @endforeach
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection